### ISSUE TITLE
Upgrade to 0.0.3 breaks bundling CSS files with Webpack

### ISSUE THREAD

**Issue by playpauseandstop** [BohdanTkachenko/webpack-split-by-path#5]
I have pretty simple structure for my project,

```
static/
- css/
  - app.css
- projectname/
  - App.js
```

And `App.js` contains an import of `../css/app.css` file,

``` js
import "../css/app.css";
```

My webpack config is pretty simple too,

``` js
  new SplitByPathPlugin([
    {
      "name": "vendors",
      "path": path.join(__dirname, "node_modules"),
    },
  ]),
```

And everything works fine with `webpack#1.12.1` and `webpack-split-by-path#0.0.2`. But when I tried to update SplitByPathPlugin to `0.0.3` version everything became broken, and I start getting weird errors in console,

```
ERROR in ./static/css/app.css
Module build failed: TypeError: undefined is not a function
    at Object.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/extract-text-webpack-plugin/loader.js:100:11)
    at Compiler.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compiler.js:214:10)
    at /Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/extract-text-webpack-plugin/loader.js:78:5)
    at Compiler.next (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/tapable/lib/Tapable.js:69:14)
    at Compiler.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compilation.js:576:13)
    at Compilation.applyPluginsAsync (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compilation.js:571:10)
    at Compilation.applyPluginsAsync (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compilation.js:566:9)
    at Compilation.applyPluginsAsync (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compilation.js:562:8)
    at Compilation.applyPluginsAsync (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.seal (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compilation.js:524:7)
    at Compiler.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compiler.js:397:15)
    at /Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compilation.js:444:10)
    at /Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compilation.js:416:12
    at /Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compilation.js:331:10
    at /Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/async/lib/async.js:248:21)
    at /Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compilation.js:331:10
    at /Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/async/lib/async.js:236:20)
    at Object.async.forEach.async.each (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/async/lib/async.js:215:22)
 @ ./static/projectname/App.js 25:0-25
```

And as result `app.css` file not built on.

So I'm wondering what changed in 0.0.3 which results breaking CSS bundling with webpack?

**Comment by BohdanTkachenko** [comment]
Hi @playpauseandstop 

It seems that it is after merging PR #4 
I will try to fix this ASAP

**Comment by BohdanTkachenko** [comment]
And also I should find some time to write tests for this module :)

**Comment by s-panferov** [comment]
@BohdanTkachenko thanks for fixing this. My team also noticed the bug.

**Comment by s-panferov** [comment]
@BohdanTkachenko the issue appears on v0.0.2 too.

**Comment by BohdanTkachenko** [comment]
@s-panferov thanks for information about v.0.0.2

**Comment by BohdanTkachenko** [comment]
@playpauseandstop @s-panferov I tried to reproduce this issue, but it works fine for sample configuration. Can you please take a look at https://github.com/BohdanTkachenko/webpack-split-by-path/commit/afa01ab6804c8e80d10d6c0706d952efe8416d77 and tell me if issue is reproducable on your machines with this configurations? Thanks.

**Comment by playpauseandstop** [comment]
Same error for me after update `webpack-split-by-path` to afa01ab6804c8e80d10d6c0706d952efe8416d77

And discovered problem with `0.0.2` version, when CSS file contains some `url(...)` statement the webpack build is failed if `webpack-split-by-path` is enabled.

Will try to add more details tomorrow.

**Comment by playpauseandstop** [comment]
I believe the problem encountered only when using `SplitByPathPlugin` together with `ExtractTextPlugin`, for more details attempt to build a bundle in [my test repo](https://github.com/playpauseandstop/webpack-split-by-path-css-error)

**Comment by playpauseandstop** [comment]
Maybe this issue related to https://github.com/webpack/extract-text-webpack-plugin/issues/92

**Comment by BohdanTkachenko** [comment]
@playpauseandstop The problem is that CSS needs css-loader which is moving to another chunk with this plugin and it cannot access css-loader. Not sure how correctly fix it, but for temporary solution I added ignore option to plugin that allows you to ignore some paths. Just pushed version 0.0.4. Please see my pull request in your test repo https://github.com/playpauseandstop/webpack-split-by-path-css-error/pull/1/files for changed files.

**Comment by playpauseandstop** [comment]
@BohdanTkachenko 

Thanks, but fix working only for my test repo. 

When I tried to switch back to `SplitByPathPlugin` from `CommonsChunkPlugin` in real project I still having errors while bundling,

```
ERROR in ./~/font-awesome/css/font-awesome.css
Module build failed: TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (/Users/playpauseandstop/Projects/projectname/node_modules/css-loader/index.js?importLoaders=1&sourceMap!/Users/playpauseandstop/Projects/projectname/node_modules/font-awesome/css/font-awesome.css:27:29)
    at Object.module.exports.module.exports (/Users/playpauseandstop/Projects/projectname/node_modules/css-loader/index.js?importLoaders=1&sourceMap!/Users/playpauseandstop/Projects/projectname/node_modules/font-awesome/css/font-awesome.css:69:29)
    at __webpack_require__ (/Users/playpauseandstop/Projects/projectname/node_modules/css-loader/index.js?importLoaders=1&sourceMap!/Users/playpauseandstop/Projects/projectname/node_modules/font-awesome/css/font-awesome.css:27:30)
    at /Users/playpauseandstop/Projects/projectname/node_modules/css-loader/index.js?importLoaders=1&sourceMap!/Users/playpauseandstop/Projects/projectname/node_modules/font-awesome/css/font-awesome.css:62:18
    at Object.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/css-loader/index.js?importLoaders=1&sourceMap!/Users/playpauseandstop/Projects/projectname/node_modules/font-awesome/css/font-awesome.css:65:10)
    at Module._compile (module.js:460:26)
    at Object.loaderContext.exec (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:88:7)
    at Object.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/extract-text-webpack-plugin/loader.js:97:22)
    at Compiler.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compiler.js:214:10)
    at /Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/extract-text-webpack-plugin/loader.js:78:5)
    at Compiler.next (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/tapable/lib/Tapable.js:69:14)
    at Compiler.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compilation.js:576:13)
    at Compilation.applyPluginsAsync (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compilation.js:571:10)
    at Compilation.applyPluginsAsync (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compilation.js:566:9)
    at Compilation.applyPluginsAsync (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compilation.js:562:8)
    at Compilation.applyPluginsAsync (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.seal (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compilation.js:524:7)
    at Compiler.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compiler.js:397:15)
    at /Users/playpauseandstop/Projects/projectname/node_modules/webpack/node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (/Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compilation.js:444:10)
    at /Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compilation.js:416:12
    at /Users/playpauseandstop/Projects/projectname/node_modules/webpack/lib/Compilation.js:331:10
 @ ./static/js/index.js 15:0-44
```

So after `0.0.4` my CSS files work well, but vendors CSS files seems like not working. Any suggestions?

---

ps. Styles loading in `index.js` as,

``` js
import "normalize.css/normalize.css";
import "font-awesome/css/font-awesome.css";

...
```

**Comment by playpauseandstop** [comment]
https://github.com/playpauseandstop/webpack-split-by-path-css-error/commit/038da58ba3e0e29c104173259ca093c7091cc3e9

**Comment by BohdanTkachenko** [comment]
What cames to my mind is that you can simply ignore all CSS files in node_modules, but in this case they will be in your main chunk, but they actually should be in vendors... So I need to think how to correctly handle this without making hacks. 

Just pushed version 0.0.5 (https://github.com/BohdanTkachenko/webpack-split-by-path/commit/d681817c519d32b05916cc1d02238451be36006f) which allows you to specify regular expression in path and in config.ignore.

Please try just to add something like /node_modules\/(*.?).css/ to config.ignore.
So it would be:

``` js
ignore: [
  path.resolve(__dirname, "node_modules/css-loader/lib/css-base.js"),
  /node_modules\/(.*?)\.css/
]
```

You can try experimenting with this regex if it won't work.

**Comment by BohdanTkachenko** [comment]
Just checked in your example - it doesn't help

**Comment by BohdanTkachenko** [comment]
Ok, I just pushed version 0.0.6 which now allows you to use config like above. Please also see PR https://github.com/playpauseandstop/webpack-split-by-path-css-error/pull/2 with changes that fix your configuration.

**Comment by playpauseandstop** [comment]
@BohdanTkachenko 

After `0.0.6` release and some tweaks to ignore patterns (https://github.com/playpauseandstop/webpack-split-by-path-css-error/commit/4598f9f407bfa010df4628ee4a3be780e83d308c) I bring `SplitByPathPlugin` back to my project's webpack config.

Thank you very much for your quick responses, I really appreciate it!
